version: "3.7"
services:
  agent:
    image: portainer/agent:2.16.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]
    restart: ${RESTART_POLICY}
  portainer:
    image: portainer/portainer-ce:2.16.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ${VOL_CONFIG}/portainer:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    restart: ${RESTART_POLICY}
  flame:
    image: pawelmalak/flame
    container_name: flame
    hostname: flame
    volumes:
      - ${VOL_CONFIG}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: ${RESTART_POLICY}
    deploy:
      mode: global
networks:
  default:
    external:
      name: intranet
  agent_network:
    driver: overlay
    attachable: true
