version: "3.7"
services:
  portainer-agent:
    image: portainer/agent:2.11.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
  portainer-server:
    image: portainer/portainer-ce:2.11.1
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    volumes:
      - ${VOL_CONFIG}/portainer:/data
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${VOL_CONFIG}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: ${RESTART_POLICY}
networks:
  default:
    external:
      name: intranet
